### ISSUE TITLE
principle point coordinate

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [mnslarcher/camera-models#3]
Hi, @estshorter Great visualization work!
But I have a question, why the principle point is not in the center of the image plane? 
From your code the origin coordinate is 
`    origin=Z.p - camera_frame.dx * PX - camera_frame.dy * PY, `
I think it should be 
`    origin=Z.p - camera_frame.dx * (IMAGE_WIDTH / 2)- camera_frame.dy * (IMAGE_HEIGHT / 2), `

**Comment by estshorter** [comment]
FYI, the author of this repository is @mnslarcher.

**Comment by mnslarcher** [comment]
Hi @KnightOfTheMoonlight ! I left it parametric (you can choose where it is). Most of the time it is actually in the center of the image, but because of camera manufacturing defects or whatever it may not be exactly there. To put it in the center you can change PX and PY in notebook, without having to rewrite the formula:

```
PX= 2.0  # principal point x-coordinate
PY= 1.0  # principal point y-coordinate
```

Does that make sense? Thanks for appreciating the repository!

**Comment by KnightOfTheMoonlight** [comment]
This makes sense.
